// checkGrammar(txt) was generated by Microsoft Copilot
const x = {"checkGrammar": async function(text) {
const response = await fetch('https://api.languagetoolplus.com/v2/check', {
method: 'POST',
headers: {
'Content-Type': 'application/x-www-form-urlencoded'
},
body: new URLSearchParams({
text: text,
language: 'en-US'
})
});

const result = await response.json();

// Format and return grammar issues

// Code by AzareelJames

const correct = result.matches.map(match => ({
message: match.message,
suggestions: match.replacements.map(r => r.value),
context: match.context.text
}));

return correct;
}
, "getIsCorrectGrammar": async function(txt){const y = await x.checkGrammar(txt); return y.length === 0}}

x;